language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.1
  - jruby-19mode
  - rbx
services: redis
before_script:
  - cd test/dummy && RAILS_ENV=test bundle exec rake db:migrate && cd -
matrix:
  allow_failures:
    - rvm: rbx
